[package]
name = "ring-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ring"
path = "src/main.rs"

[dependencies]
axum = { version = "0.8", features = ["ws", "multipart"] }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ulid = { version = "1", features = ["serde"] }
tower-http = { version = "0.6", features = ["cors", "fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
tower = "0.5"
async-openai = "0.27"
tokio-stream = "0.1"
futures-util = "0.3"
async-stream = "0.3"
dashmap = "6"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
url = "2"
urlencoding = "2"
serde_yaml = "0.9"
rand = "0.9"
base64 = "0.22"
magic-crypt = "4.0"
aes-gcm = { version = "0.10", features = ["aes"] }
regex = "1"
flate2 = { version = "1.1.9", features = ["default"] }
tar = "0.4.45"
pdf-extract = "0.10"
async-trait = "0.1.89"
include_dir = { version = "0.7", features = ["glob"] }
mime_guess = "2"

[dev-dependencies]
tempfile = "3"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
